---
# tasks file for dhparams
- name: Create dhparams directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0600
  with_items:
    - '{{ dhparam_location }}'
- name: Create SSL dhparams file
  command: "{{ item.command }} creates={{ item.file }}"
  with_items:
    - { command: 'openssl dhparam -out {{ dhparam_location }}/{{ dhparam_file }} {{ dhparam_bytes }}',
        file: '{{ dhparam_location }}/{{ dhparam_file }}'
      }
